build:
  id: 101
  version: 1.2.3
  name: "Native Default-Default-Build"
  type: "Native Default Build"

management:
  endpoints:
    web:
      exposure:
        include: refresh

#  BUILD_ID=4444;BUILD_NAME=NAME_TEST;BUILD_VERSION=1.0.0
# ID=9999;NAME=NEW_NAME;VERSION=3.3.3.3